// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQq30OcviXwUOD0bfPWFYymhbyhpDHjBg',
    appId: '1:984587538070:web:e3f3df2abb7453c7cd3cb7',
    messagingSenderId: '984587538070',
    projectId: 'testapp5-c8137',
    authDomain: 'testapp5-c8137.firebaseapp.com',
    storageBucket: 'testapp5-c8137.firebasestorage.app',
    measurementId: 'G-XN00EFG1F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKCtaLYiuYyEjRL7gMwe84eO_QK4EafA',
    appId: '1:984587538070:android:88b2537511036054cd3cb7',
    messagingSenderId: '984587538070',
    projectId: 'testapp5-c8137',
    storageBucket: 'testapp5-c8137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVzw5KgXJCv8QnL5LL41WSqxCeEa1G6UY',
    appId: '1:984587538070:ios:06f4b9efbbf73911cd3cb7',
    messagingSenderId: '984587538070',
    projectId: 'testapp5-c8137',
    storageBucket: 'testapp5-c8137.firebasestorage.app',
    iosBundleId: 'com.example.testapp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVzw5KgXJCv8QnL5LL41WSqxCeEa1G6UY',
    appId: '1:984587538070:ios:06f4b9efbbf73911cd3cb7',
    messagingSenderId: '984587538070',
    projectId: 'testapp5-c8137',
    storageBucket: 'testapp5-c8137.firebasestorage.app',
    iosBundleId: 'com.example.testapp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQq30OcviXwUOD0bfPWFYymhbyhpDHjBg',
    appId: '1:984587538070:web:021bba1647cf2129cd3cb7',
    messagingSenderId: '984587538070',
    projectId: 'testapp5-c8137',
    authDomain: 'testapp5-c8137.firebaseapp.com',
    storageBucket: 'testapp5-c8137.firebasestorage.app',
    measurementId: 'G-KDD45CFQCZ',
  );
}
